export function readConfig(raw = {}) {
  return {
    enabled: raw.enabled !== false,
    mode: raw.mode === 'observe' ? 'observe' : 'revise',
    injectPrompt: raw.injectPrompt !== false,
    strictTools: raw.strictTools !== false,
    midRunReflection: raw.midRunReflection !== false,
    semanticReview: raw.semanticReview !== false,
    longTaskMode: raw.longTaskMode !== false,
    autonomousRecovery: raw.autonomousRecovery !== false,
    enforceAutonomousRecovery: raw.enforceAutonomousRecovery !== false,
    skillHints: raw.skillHints !== false,
    implicitPlanFiles: raw.implicitPlanFiles !== false,
    projectPlanFiles: raw.projectPlanFiles !== false,
    cleanupPlanOnSuccess: raw.cleanupPlanOnSuccess === true,
    persistLedger: raw.persistLedger !== false,
    ledgerPromptMode: ['none', 'redacted', 'full'].includes(raw.ledgerPromptMode) ? raw.ledgerPromptMode : 'redacted',
    maxLedgerBytes: Number.isFinite(raw.maxLedgerBytes) ? Math.max(10000, Math.min(5_000_000, Math.trunc(raw.maxLedgerBytes))) : 1_000_000,
    retentionDays: Number.isFinite(raw.retentionDays) ? Math.max(1, Math.min(365, Math.trunc(raw.retentionDays))) : 30,
    reviewerMode: ['rules', 'llm', 'hybrid'].includes(raw.reviewerMode) ? raw.reviewerMode : 'rules',
    codingStrict: raw.codingStrict !== false,
    evidenceScoring: raw.evidenceScoring !== false,
    oracleStrict: raw.oracleStrict !== false,
    changedLinesReview: raw.changedLinesReview !== false,
    docLocaleConsistency: raw.docLocaleConsistency !== false,
    blockHighRiskTools: raw.blockHighRiskTools !== false,
    approvalMode: ['approval', 'block'].includes(raw.approvalMode) ? raw.approvalMode : 'approval',
    milestoneReflectionEveryTools: Number.isFinite(raw.milestoneReflectionEveryTools) ? Math.max(3, Math.min(20, Math.trunc(raw.milestoneReflectionEveryTools))) : 5,
    failureBudget: Number.isFinite(raw.failureBudget) ? Math.max(1, Math.min(5, Math.trunc(raw.failureBudget))) : 3,
    maxRevisionAttempts: Number.isFinite(raw.maxRevisionAttempts) ? Math.max(0, Math.min(3, Math.trunc(raw.maxRevisionAttempts))) : 1,
    debug: raw.debug === true,
  };
}

